---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1276530/public_html/api/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R application/ $DEPLOYPATH
    - /bin/cp -R system/ $DEPLOYPATH